### Test Development Environment
# Run: APP_ENV=development go run main.go

GET http://localhost:3020/
GET http://localhost:3020/status

---

### Test Staging Environment
# Run: APP_ENV=staging go run main.go

GET http://localhost:3020/
GET http://localhost:3020/status

---

### Test Production Environment
# Run: APP_ENV=production go run main.go

GET http://localhost:3020/
GET http://localhost:3020/status
