# Valid Lokstra Configuration Example
# This file demonstrates all available configuration options with proper schema validation

# General configurations (key-value pairs)
configs:
  - name: app-version
    value: "1.0.0"
  - name: environment
    value: "production"
  - name: debug-mode
    value: false
  - name: max-connections
    value: 100

# Service configurations
services:
  - name: database
    type: postgres
    enable: true
    config:
      host: localhost
      port: 5432
      database: myapp
      username: admin
      
  - name: redis-cache
    type: redis
    enable: true
    config:
      host: localhost
      port: 6379
      
  - name: email-service
    type: smtp
    enable: false  # Disabled service
    config:
      host: smtp.gmail.com
      port: 587

# Middleware configurations
middlewares:
  - name: cors
    type: cors
    enable: true
    config:
      allowOrigins: 
        - "*"
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
      allowHeaders:
        - Content-Type
        - Authorization
        
  - name: rate-limiter
    type: rate-limit
    enable: true
    config:
      requestsPerMinute: 60
      
  - name: logger
    type: logging
    config:
      level: info
      format: json

# Server configurations
servers:
  - name: main-api-server
    baseUrl: http://localhost
    deployment-id: production-cluster-01
    apps:
      - name: public-api
        addr: :8080
        listener-type: default
        routers:
          - product-api
          - order-api
          - user-api
          
      - name: admin-api
        addr: :8081
        listener-type: default
        routers:
          - admin-router
          
  - name: internal-services
    baseUrl: http://internal.example.com
    deployment-id: production-cluster-01
    apps:
      - name: analytics-service
        addr: :9000
        routers:
          - analytics-router
          
      - name: notification-service
        addr: :9001
        listener-type: websocket
        routers:
          - notification-router
