# Invalid Lokstra Configuration Examples
# These demonstrate common validation errors

# ❌ ERROR: Missing required 'name' field in server
servers:
  - baseUrl: http://localhost
    apps:
      - addr: :8080

---
# ❌ ERROR: Missing required 'apps' field in server
servers:
  - name: invalid-server
    baseUrl: http://localhost

---
# ❌ ERROR: Empty apps array (minimum 1 required)
servers:
  - name: invalid-server
    apps: []

---
# ❌ ERROR: Missing required 'addr' field in app
servers:
  - name: test-server
    apps:
      - name: api
        routers:
          - some-router

---
# ❌ ERROR: Invalid baseUrl format (must be http:// or https://)
servers:
  - name: test-server
    baseUrl: invalid-url
    apps:
      - addr: :8080

---
# ❌ ERROR: Missing required 'type' field in service
services:
  - name: database
    config:
      host: localhost

---
# ❌ ERROR: Missing required 'type' field in middleware
middlewares:
  - name: cors
    config:
      allowOrigins: ["*"]

---
# ❌ ERROR: Missing required 'value' field in config
configs:
  - name: app-version

---
# ❌ ERROR: Empty name not allowed
servers:
  - name: ""
    apps:
      - addr: :8080

---
# ❌ ERROR: Empty addr not allowed
servers:
  - name: test-server
    apps:
      - addr: ""
