# API Gateway Example with Reverse Proxy Configuration
# This demonstrates how to configure an app as a pure reverse proxy gateway

servers:
  - name: api-gateway
    base-url: http://localhost
    apps:
      # Pure reverse proxy gateway (no routers)
      - name: gateway
        addr: ":8080"
        reverse-proxies:
          # Forward /api/* to backend API server
          - prefix: /api
            strip-prefix: true
            target: http://api-server:8080
          
          # Forward /auth/* to auth service (keep prefix)
          - prefix: /auth
            strip-prefix: false
            target: http://auth-service:9000
          
          # Forward /v2/* to new API version
          - prefix: /v2
            strip-prefix: true
            target: http://api-v2:8081

---
# Mixed mode: Reverse proxy + regular routers
servers:
  - name: hybrid-gateway
    base-url: http://localhost
    apps:
      - name: hybrid
        addr: ":8090"
        # Reverse proxies are mounted first
        reverse-proxies:
          - prefix: /external
            strip-prefix: true
            target: http://external-api:8080
        
        # Then regular routers are mounted
        routers:
          - internal-router

routers:
  - name: internal-router
    path-prefix: /internal
