# yaml-language-server: $schema=https://lokstra.dev/schema/lokstra.json

server:
  name: "YAML Configuration Demo Server"
  global_setting:
    log_level: "${LOG_LEVEL:info}"
    debug_mode: "${DEBUG_MODE:false}"

services:
  - name: "app-logger"
    type: "logger"
    config:
      level: "info"
      format: "json"
      output: "stdout"
      
  - name: "debug-logger"
    type: "logger"
    config:
      level: "debug"
      format: "text"
      output: "stdout"

apps:
  - name: "main-app"
    address: "${API_HOST:localhost}:${API_PORT:8080}"
    listener_type: "nethttp"
    router_engine_type: "gin"
    
    middleware:
      - name: "timing"
        enabled: true
      - name: "recovery"
        enabled: true
      - name: "cors"
        enabled: true
        config:
          allow_origins: ["*"]
          allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          allow_headers: ["*"]

    routes:
      - method: "GET"
        path: "/"
        handler: "home"
        
      - method: "GET"
        path: "/health"
        handler: "health_check"
        
      - method: "GET"
        path: "/config-info"
        handler: "config_info"
        
      - method: "POST"
        path: "/api/data"
        handler: "data_handler"
        middleware:
          - name: "validate_content"
            enabled: true
            
      - method: "GET"
        path: "/api/protected/profile"
        handler: "protected_profile"
        middleware:
          - name: "custom_auth"
            enabled: true