// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package repository

import (
	"github.com/primadi/lokstra/lokstra_registry"
)

// Auto-register on package import
func init() {
	RegisterUserRepositoryImpl()
}

// ============================================================
// FILE: user_repository.go
// ============================================================

// RegisterUserRepositoryImpl registers the user-repository with the registry
// Auto-generated from annotations:
//   - @Service name="user-repository"
func RegisterUserRepositoryImpl() {
	lokstra_registry.RegisterLazyService("user-repository", func(deps map[string]any, cfg map[string]any) any {
		svc := &UserRepositoryImpl{
		}
		
		// Call Init() for post-initialization
		if err := svc.Init(); err != nil {
			panic("failed to initialize user-repository: " + err.Error())
		}
		
		return svc
	}, map[string]any{
	})
}


