# Microservices Deployment - Product Service
# Independent product service with its own database and caching

configs:
  - name: deployment-type
    value: "microservices"
  - name: service-name
    value: "product-service"
  - name: user-service-url
    value: "${USER_SERVICE_URL:http://localhost:8083}"
  - name: payment-service-url
    value: "${PAYMENT_SERVICE_URL:http://localhost:8084}"
  - name: analytics-service-url
    value: "${ANALYTICS_SERVICE_URL:http://localhost:8085}"
  - name: cors-origins
    value: "${CORS_ORIGINS:*}"
  - name: rate-limit-rps
    value: 500
  - name: cache-ttl-seconds
    value: 600  # Longer cache for product data
  - name: enable-cache
    value: true
  - name: database-url
    value: "${PRODUCT_DB_URL:postgres://localhost:5432/products}"
  - name: database-pool-size
    value: 10
  - name: redis-url
    value: "${PRODUCT_REDIS_URL:redis://localhost:6379/0}"

middlewares:
  - name: logging
    type: logging
  - name: cors
    type: cors  
  - name: rate-limit
    type: rate-limit
  - name: cache
    type: cache

services:
  - name: database
    type: database
  - name: redis  
    type: redis
  # Business services - will use HTTP clients in microservices
  - name: product-service
    type: product-service
  - name: user-service
    type: user-service
  - name: payment-service
    type: payment-service
  - name: analytics-service
    type: analytics-service

routers:
  - name: product-api
    use: [logging, cors, cache]
    routes:
      - name: products-list
        use: [rate-limit]

servers:
  - name: product-service
    listen: "${PRODUCT_PORT:8081}"
    services: [database, redis, product-service, user-service, payment-service, analytics-service]
    apps:
      - name: product-app
        addr: "/"
        routers: [product-api]