# ===== GLOBAL DEFINITIONS =====
# These are shared across all deployments

# Configuration values
configs:
  # Database connections
  - name: DB_USER_URL
    value: ${DB_USER_URL:postgres://localhost/users}
  
  - name: DB_ORDER_URL
    value: ${DB_ORDER_URL:postgres://localhost/orders}
  
  - name: DB_MAX_CONNS
    value: 20
  
  # Authentication
  - name: JWT_SECRET
    value: ${JWT_SECRET:dev-secret-key}
  
  # Logging
  - name: LOG_LEVEL
    value: ${LOG_LEVEL:info}
  
  - name: SLOW_QUERY_MS
    value: 100

# Middleware definitions
middlewares:
  - name: cors
    type: cors-middleware
    config:
      origins: ["*"]
  
  - name: auth
    type: jwt-auth
    config:
      secret: ${@cfg:JWT_SECRET}
  
  - name: rate-limit
    type: rate-limiter
    config:
      requests-per-second: 100
  
  - name: slow-logger
    type: slow-query-logger
    config:
      threshold: ${@cfg:SLOW_QUERY_MS}

# Service definitions
services:
  # Database pools
  - name: db-user
    type: dbpool_pg
    config:
      dsn: ${DB_USER_URL}
      max-conns: ${@cfg:DB_MAX_CONNS}
  
  - name: db-order
    type: dbpool_pg
    config:
      dsn: ${DB_ORDER_URL}
      max-conns: ${@cfg:DB_MAX_CONNS}
  
  # Application services
  - name: user-service
    type: user-factory
    depends-on: [db-user, logger]
  
  - name: order-service
    type: order-factory
    depends-on: ["dbOrder:db-order", "userSvc:user-service", logger]
  
  # Infrastructure services
  - name: logger
    type: logger-factory
    config:
      level: ${@cfg:LOG_LEVEL}
      format: json

# Manual routers (created in code)
routers:
  - name: health-router
  - name: metrics-router

# Router overrides
router-overrides:
  # Public API - limited access
  - name: user-public-api
    path-prefix: /api/v1
    middlewares: [cors]
    hidden: [Delete, BulkDelete, AdminReset]
    routes:
      - name: Create
        path: /register
        middlewares: [rate-limit]
      - name: Update
        middlewares: [auth]
      - name: GetByID
        middlewares: [auth]
  
  # Admin API - full access
  - name: user-admin-api
    path-prefix: /admin/api/v1
    middlewares: [cors, auth]
  
  - name: order-public-api
    path-prefix: /api/v1
    middlewares: [cors, auth]

# Service routers (auto-generated from services)
service-routers:
  - name: user-service-public
    service: user-service
    convention: rest
    overrides: user-public-api
  
  - name: user-service-admin
    service: user-service
    convention: rest
    overrides: user-admin-api
  
  - name: order-service-public
    service: order-service
    convention: rest
    overrides: order-public-api

# ===== DEPLOYMENTS =====
# Select and arrange from global definitions

deployments:
  # Monolith: Everything in one server
  - name: monolith
    servers:
      - name: main-server
        base-url: http://localhost
        apps:
          - port: 3000
            services: [db-user, db-order, user-service, order-service, logger]
            routers: [health-router, metrics-router]
            service-routers:
              - name: user-service-public
              - name: order-service-public
  
  # Microservices: Split across servers
  - name: microservices
    servers:
      # User service server
      - name: user-server
        base-url: http://localhost
        apps:
          - port: 3001
            services: [db-user, user-service, logger]
            routers: [health-router]
            service-routers:
              - name: user-service-admin
      
      # Order service server
      - name: order-server
        base-url: http://localhost
        apps:
          - port: 3002
            services: [db-order, order-service, logger]
            routers: [health-router]
            service-routers:
              - name: order-service-public
            
            # Remote services (proxy to user-service)
            remote-services:
              - name: user-service
                url: http://localhost:3001
                service-router: user-service-admin
  
  # Development: Override configs for local development
  - name: dev
    config-overrides:
      LOG_LEVEL: debug
      DB_MAX_CONNS: 5
      SLOW_QUERY_MS: 50
    
    servers:
      - name: dev-server
        base-url: http://localhost
        apps:
          - port: 3000
            services: [db-user, db-order, user-service, order-service, logger]
            routers: [health-router]
            service-routers:
              - name: user-service-public
              - name: order-service-public
  
  # Production: Different config values
  - name: prod
    config-overrides:
      LOG_LEVEL: error
      DB_MAX_CONNS: 100
      SLOW_QUERY_MS: 200
      JWT_SECRET: ${@aws-ssm:/prod/jwt-secret}
      DB_USER_URL: ${@aws-ssm:/prod/db/user-url}
      DB_ORDER_URL: ${@aws-ssm:/prod/db/order-url}
    
    servers:
      - name: prod-server
        base-url: https://api.example.com
        apps:
          - port: 80
            services: [db-user, db-order, user-service, order-service, logger]
            routers: [health-router, metrics-router]
            service-routers:
              - name: user-service-admin
              - name: order-service-public
