# yaml-language-server: $schema=https://primadi.github.io/lokstra/schema/lokstra.schema.json

# Configuration with CFG references - DRY principle

# Define shared config values
configs:
  database.host: localhost
  database.port: 5432
  database.username: admin
  database.password: secret123
  
  api.version: v1
  api.base_path: /api
  api.timeout: 30s
  
  features.enable_auth: true
  features.enable_logging: true
  features.enable_metrics: false

# Use CFG references in service definitions
service-definitions:
  postgres-service:
    type: postgres-factory
    config:
      host: "${@cfg:database.host}"
      port: "${@cfg:database.port}"
      user: "${@cfg:database.username}"
      password: "${@cfg:database.password}"
      database: myapp

  cache-service:
    type: redis-factory
    config:
      host: "${@cfg:database.host}"  # Reuse database host
      port: 6379

  user-service:
    type: user-service-factory
    depends-on:
      - postgres-service

# Define routers with path-prefix using CFG references
router-definitions:
  user-service-router:
    convention: rest
    resource: user
    resource-plural: users
    path-prefix: "${@cfg:api.base_path}/${@cfg:api.version}"

# Define deployment
deployments:
  local:
    servers:
      web-server:
        base-url: http://localhost:8080
        apps:
          - addr: ":8080"
            routers:
              - user-service-router
