# Valid Configuration
# Has all required fields

configs:
  - name: app_name
    value: "My Application"
  - name: app_version
    value: "1.0.0"
  - name: db_host
    value: "localhost:5432"
  - name: db_name
    value: "myapp"
  - name: log_level
    value: "INFO"
