# Order Service specific configuration
deployment-type: microservices
server-name: order-service
server-port: 8082

# Router integration settings
router-timeout: 30
router-retry-count: 3
router-circuit-breaker: true

# Remote router URLs
product-service-url: http://localhost:8081