# Microservices deployment configuration
deployment-type: microservices
server-name: all
server-port: 8080

# Router integration settings
router-timeout: 30
router-retry-count: 3
router-circuit-breaker: true

# Service URLs (application-specific)
product-service-url: http://localhost:8081
order-service-url: http://localhost:8082
user-service-url: http://localhost:8083
payment-service-url: http://localhost:8084
analytics-service-url: http://localhost:8085