# Product Service specific configuration
deployment-type: microservices
server-name: product-service
server-port: 8081

# Router integration settings
router-timeout: 30
router-retry-count: 3
router-circuit-breaker: true

# Remote router URLs
order-service-url: http://localhost:8082