### Complete Test Suite for 69 Handler Forms
# Run: go run main.go
# Server: http://localhost:8080

### ===== GROUP 1: No Input - func() (Handlers 01-11) =====

### Handler 01: func() error
GET http://localhost:8080/h01

### Handler 02: func() any
GET http://localhost:8080/h02

### Handler 03: func() (any, error)
GET http://localhost:8080/h03

### Handler 04: func() *response.Response
GET http://localhost:8080/h04

### Handler 05: func() response.Response
GET http://localhost:8080/h05

### Handler 06: func() *response.ApiHelper
GET http://localhost:8080/h06

### Handler 07: func() response.ApiHelper
GET http://localhost:8080/h07

### Handler 08: func() (*response.Response, error)
GET http://localhost:8080/h08

### Handler 09: func() (response.Response, error)
GET http://localhost:8080/h09

### Handler 10: func() (*response.ApiHelper, error)
GET http://localhost:8080/h10

### Handler 11: func() (response.ApiHelper, error)
GET http://localhost:8080/h11

### ===== GROUP 2: Context Only - func(*request.Context) (Handlers 12-22) =====

### Handler 12: func(*request.Context) error
GET http://localhost:8080/h12

### Handler 13: func(*request.Context) any
GET http://localhost:8080/h13

### Handler 14: func(*request.Context) (any, error)
GET http://localhost:8080/h14

### Handler 15: func(*request.Context) *response.Response
GET http://localhost:8080/h15

### Handler 16: func(*request.Context) response.Response
GET http://localhost:8080/h16

### Handler 17: func(*request.Context) *response.ApiHelper
GET http://localhost:8080/h17

### Handler 18: func(*request.Context) response.ApiHelper
GET http://localhost:8080/h18

### Handler 19: func(*request.Context) (*response.Response, error)
GET http://localhost:8080/h19

### Handler 20: func(*request.Context) (response.Response, error)
GET http://localhost:8080/h20

### Handler 21: func(*request.Context) (*response.ApiHelper, error)
GET http://localhost:8080/h21

### Handler 22: func(*request.Context) (response.ApiHelper, error)
GET http://localhost:8080/h22

### ===== GROUP 3: Context + *Param - func(*request.Context, *Param) (Handlers 23-33) =====

### Handler 23: func(*request.Context, *Param) error
GET http://localhost:8080/h23/100?name=Alice
X-API-Key: key-23

### Handler 24: func(*request.Context, *Param) any
GET http://localhost:8080/h24/101?name=Bob
X-API-Key: key-24

### Handler 25: func(*request.Context, *Param) (any, error)
GET http://localhost:8080/h25/102?name=Charlie
X-API-Key: key-25

### Handler 26: func(*request.Context, *Param) *response.Response
GET http://localhost:8080/h26/103?name=David
X-API-Key: key-26

### Handler 27: func(*request.Context, *Param) response.Response
GET http://localhost:8080/h27/104?name=Eve
X-API-Key: key-27

### Handler 28: func(*request.Context, *Param) *response.ApiHelper
GET http://localhost:8080/h28/105?name=Frank
X-API-Key: key-28

### Handler 29: func(*request.Context, *Param) response.ApiHelper
GET http://localhost:8080/h29/106?name=Grace
X-API-Key: key-29

### Handler 30: func(*request.Context, *Param) (*response.Response, error)
GET http://localhost:8080/h30/107?name=Henry
X-API-Key: key-30

### Handler 31: func(*request.Context, *Param) (response.Response, error)
GET http://localhost:8080/h31/108?name=Ivy
X-API-Key: key-31

### Handler 32: func(*request.Context, *Param) (*response.ApiHelper, error)
GET http://localhost:8080/h32/109?name=Jack
X-API-Key: key-32

### Handler 33: func(*request.Context, *Param) (response.ApiHelper, error)
GET http://localhost:8080/h33/110?name=Kate
X-API-Key: key-33

### ===== GROUP 4: Context + Param - func(*request.Context, Param) (Handlers 34-44) =====

### Handler 34: func(*request.Context, Param) error
GET http://localhost:8080/h34/200?name=Liam
X-API-Key: key-34

### Handler 35: func(*request.Context, Param) any
GET http://localhost:8080/h35/201?name=Mia
X-API-Key: key-35

### Handler 36: func(*request.Context, Param) (any, error)
GET http://localhost:8080/h36/202?name=Noah
X-API-Key: key-36

### Handler 37: func(*request.Context, Param) *response.Response
GET http://localhost:8080/h37/203?name=Olivia
X-API-Key: key-37

### Handler 38: func(*request.Context, Param) response.Response
GET http://localhost:8080/h38/204?name=Peter
X-API-Key: key-38

### Handler 39: func(*request.Context, Param) *response.ApiHelper
GET http://localhost:8080/h39/205?name=Quinn
X-API-Key: key-39

### Handler 40: func(*request.Context, Param) response.ApiHelper
GET http://localhost:8080/h40/206?name=Rachel
X-API-Key: key-40

### Handler 41: func(*request.Context, Param) (*response.Response, error)
GET http://localhost:8080/h41/207?name=Sam
X-API-Key: key-41

### Handler 42: func(*request.Context, Param) (response.Response, error)
GET http://localhost:8080/h42/208?name=Tina
X-API-Key: key-42

### Handler 43: func(*request.Context, Param) (*response.ApiHelper, error)
GET http://localhost:8080/h43/209?name=Uma
X-API-Key: key-43

### Handler 44: func(*request.Context, Param) (response.ApiHelper, error)
GET http://localhost:8080/h44/210?name=Victor
X-API-Key: key-44

### ===== GROUP 5: *Param Only - func(*Param) (Handlers 45-55) =====

### Handler 45: func(*Param) error
GET http://localhost:8080/h45/300?name=Wendy
X-API-Key: key-45

### Handler 46: func(*Param) any
GET http://localhost:8080/h46/301?name=Xander
X-API-Key: key-46

### Handler 47: func(*Param) (any, error)
GET http://localhost:8080/h47/302?name=Yara
X-API-Key: key-47

### Handler 48: func(*Param) *response.Response
GET http://localhost:8080/h48/303?name=Zane
X-API-Key: key-48

### Handler 49: func(*Param) response.Response
GET http://localhost:8080/h49/304?name=Amy
X-API-Key: key-49

### Handler 50: func(*Param) *response.ApiHelper
GET http://localhost:8080/h50/305?name=Ben
X-API-Key: key-50

### Handler 51: func(*Param) response.ApiHelper
GET http://localhost:8080/h51/306?name=Cara
X-API-Key: key-51

### Handler 52: func(*Param) (*response.Response, error)
GET http://localhost:8080/h52/307?name=Dan
X-API-Key: key-52

### Handler 53: func(*Param) (response.Response, error)
GET http://localhost:8080/h53/308?name=Emma
X-API-Key: key-53

### Handler 54: func(*Param) (*response.ApiHelper, error)
GET http://localhost:8080/h54/309?name=Finn
X-API-Key: key-54

### Handler 55: func(*Param) (response.ApiHelper, error)
GET http://localhost:8080/h55/310?name=Gina
X-API-Key: key-55

### ===== GROUP 6: Param Only - func(Param) (Handlers 56-66) =====

### Handler 56: func(Param) error
GET http://localhost:8080/h56/400?name=Hugo
X-API-Key: key-56

### Handler 57: func(Param) any
GET http://localhost:8080/h57/401?name=Iris
X-API-Key: key-57

### Handler 58: func(Param) (any, error)
GET http://localhost:8080/h58/402?name=Jake
X-API-Key: key-58

### Handler 59: func(Param) *response.Response
GET http://localhost:8080/h59/403?name=Kara
X-API-Key: key-59

### Handler 60: func(Param) response.Response
GET http://localhost:8080/h60/404?name=Leo
X-API-Key: key-60

### Handler 61: func(Param) *response.ApiHelper
GET http://localhost:8080/h61/405?name=Maya
X-API-Key: key-61

### Handler 62: func(Param) response.ApiHelper
GET http://localhost:8080/h62/406?name=Nina
X-API-Key: key-62

### Handler 63: func(Param) (*response.Response, error)
GET http://localhost:8080/h63/407?name=Owen
X-API-Key: key-63

### Handler 64: func(Param) (response.Response, error)
GET http://localhost:8080/h64/408?name=Pam
X-API-Key: key-64

### Handler 65: func(Param) (*response.ApiHelper, error)
GET http://localhost:8080/h65/409?name=Quinn
X-API-Key: key-65

### Handler 66: func(Param) (response.ApiHelper, error)
GET http://localhost:8080/h66/410?name=Ruby
X-API-Key: key-66

### ===== SPECIAL FORMS (Handlers 67-69) =====

### Handler 67: http.Handler
GET http://localhost:8080/h67

### Handler 68: http.HandlerFunc
GET http://localhost:8080/h68

### Handler 69: request.HandlerFunc
GET http://localhost:8080/h69
