# services.yaml - Application services
#
# This file defines application-level services with their dependencies.
# It will be merged with base.yaml to create the complete service graph.

services:
  user-service:
    type: user-service-factory
    depends-on:
      - db:db-pool
      - logger
      - cache
    config:
      enable-caching: true
      cache-ttl: 3600

  order-service:
    type: order-service-factory
    depends-on:
      - dbOrder:db-pool
      - userSvc:user-service
      - logger
    config:
      enable-validation: true
