# Prometheus Configuration for Lokstra Metrics
# Save this as prometheus.yml and run: prometheus --config.file=prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add any alerting or recording rules here
  # - "lokstra_rules.yml"

scrape_configs:
  # Scrape Lokstra metrics service
  - job_name: 'lokstra-user-api'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
    # Optional: Add custom labels to all scraped metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'user-api-dev'
      - target_label: team
        replacement: 'backend'
    
  # Scrape multiple Lokstra instances (if running multiple services)
  - job_name: 'lokstra-services'
    static_configs:
      - targets: 
          - 'localhost:9090'  # user-api metrics
          - 'localhost:9091'  # auth-api metrics  
          - 'localhost:9092'  # payment-api metrics
    metrics_path: '/metrics'
    scrape_interval: 15s
    
    # Service discovery labels
    relabel_configs:
      - source_labels: [__address__]
        regex: 'localhost:9090'
        target_label: service_name
        replacement: 'user-api'
      - source_labels: [__address__]
        regex: 'localhost:9091'
        target_label: service_name
        replacement: 'auth-api'
      - source_labels: [__address__]
        regex: 'localhost:9092'
        target_label: service_name
        replacement: 'payment-api'

  # Example: Scrape from Consul service discovery
  # - job_name: 'lokstra-consul'
  #   consul_sd_configs:
  #     - server: 'localhost:8500'
  #       services: ['lokstra-api']
  #   relabel_configs:
  #     - source_labels: [__meta_consul_service]
  #       target_label: service
  #     - source_labels: [__meta_consul_node]
  #       target_label: node

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - "localhost:9093"  # Alertmanager instance
