# Monolith Deployment Configuration (V2 - with auto-router)
# All services run in a single process on one port
# Best for: Development, small applications

configs:
  - name: app_name
    value: "E-Commerce Monolith V2"
  - name: current-server
    value: "server-02" 
    
# Define all services with auto-router configuration
services:
  - name: user-service
    type: user_service
    auto-router:
      convention: "rest"
      path-prefix: "/api/v1"
      # resource-name: "user"
    config:
      storage: memory
      
  - name: auth-service
    type: auth_service
    auto-router:
      convention: "rest"
      path-prefix: "/api/v1"
      resource-name: "auth"
      routes:
        - name: Login
          method: POST
          path: "/login"
        - name: Logout
          method: POST
          path: "/logout"
        - name: ValidateToken
          method: POST
          path: "/validate-token"
    depends-on: [user-service]
    config:
      jwt_secret: dev-secret-key
      token_expiry: 3600

  - name: order-service
    type: order_service
    auto-router:
      convention: "rest"
      path-prefix: "/api/v1"
      resource-name: "order"
    depends-on: [user_service:user-service, payment_service:payment-service]
    config:
      storage: memory
      max_items_per_order: 100
    
  - name: cart-service
    type: cart_service
    auto-router:
      convention: "rest"
      path-prefix: "/api/v1"
      resource-name: "cart"
    depends-on: [user_service:user-service]
    config:
      storage: memory
      session_timeout: 1800

  - name: payment-service
    type: payment_service
    auto-router:
      convention: "rest"
      path-prefix: "/api/v1"
      resource-name: "payment"
      routes:
        - name: ProcessPayment
          method: POST
          path: "/payments"
    depends-on: [user_service:user-service]
    config:
      storage: memory
      currency: USD
    
  - name: invoice-service
    type: invoice_service
    auto-router:
      convention: "rest"
      path-prefix: "/api/v1"
      routes:
        - name: GenerateInvoice
          method: POST
          path: "/invoices"
    depends-on: [payment_service:payment-service] 
    config:
      storage: memory

middlewares:
  - name: logger
    type: request_logger
    config:
      format: "text"
      log_level: "debug"

# Single server with all services
servers:
  - name: monolith
    base-url: http://localhost
    deployment-id: monolith
    apps:
      - name: monolith-app
        addr: ":8080"
        # Services available locally
        services:
          - user-service
          - auth-service
          - order-service
          - cart-service
          - payment-service
          - invoice-service
        # Services published as HTTP API
        routers:
          - user-service
          - auth-service
          - order-service
          - cart-service
          - payment-service
          - invoice-service
        middlewares: [logger]
  - name: monolith-multi-port
    base-url: http://localhost
    deployment-id: monolith-multi-port
    apps:
      - name: monolith-app-01
        addr: ":8081"
        # Services available locally
        services:
          - user-service
          - auth-service
          - order-service
        # Services published as HTTP API
        routers:
          - user-service
          - auth-service
          - order-service
        middlewares: [logger]
      - name: monolith-app-02
        addr: ":8082"
        # Services available locally
        services:
          - cart-service
          - payment-service
          - invoice-service
        # Services published as HTTP API
        routers:
          - cart-service
          - payment-service
          - invoice-service
        middlewares: [logger]
  - name: server-01
    base-url: http://localhost
    deployment-id: two-servers
    apps:
      - addr: ":8081"
        # Services available locally
        services:
          - user-service
          - auth-service
          - order-service
        # Services published as HTTP API
        routers:
          - user-service
          - auth-service
          - order-service
        middlewares: [logger]
  - name: server-02
    base-url: http://localhost
    deployment-id: two-servers
    apps:      
      - addr: ":8082"
        # Services available locally
        services:
          - cart-service
          - payment-service
          - invoice-service
        # Services published as HTTP API
        routers:
          - cart-service
          - payment-service
          - invoice-service
        middlewares: [logger]
