# Monolith Single Port Configuration
# All services run in one process on one port
# Simple deployment, minimal infrastructure

configs:
  - name: server-name
    value: ${SERVER_NAME:monolith-single-server}
  
  - name: deployment-strategy
    value: monolith-single-port

# All infrastructure and domain services
services:
  - name: db-service
    type: db
    config:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:5432}
      database: ${DB_NAME:ecommerce}

  - name: cache-service
    type: cache
    config:
      host: ${CACHE_HOST:localhost}
      port: ${CACHE_PORT:6379}

  - name: product-service
    type: product
    config: {}

  - name: order-service
    type: order
    config: {}

  - name: user-service
    type: user
    config: {}

# Single server, single app, single port
# All routers served from same address
servers:
  - name: monolith-single-server
    baseUrl: http://localhost
    deployment-id: monolith-single-port
    apps:
      - addr: ":8080"
        routers: [product-api, order-api, user-api, health-api]

# Benefits:
# ✅ Simplest deployment
# ✅ No network overhead between services
# ✅ Easy to develop and test
# ✅ Single process to monitor
# ✅ Lower infrastructure cost
#
# Use when:
# - Starting a new project
# - Small to medium traffic
# - Team < 10 developers
# - Cost is a concern
#
# Communication:
# - All routers: Local (httptest) - zero network calls
