# language-server: $schema=https://primadi.github.io/lokstra/schema/lokstra.schema.json

# Base configuration - shared across all environments
routers:
  - name: api
    routes:
      - path: /health
        handler: HealthCheckHandler
        method: GET
      - path: /info
        handler: InfoHandler
        method: GET

servers:
  - name: ${APP_NAME:my-app}
    address: ${APP_HOST:localhost}:${APP_PORT:8080}
    apps:
      - name: main-app
        routers:
          - api
