# Monolith Deployment Configuration
# All services run in a single process on one port
# Best for: Development, small applications

configs:
  - name: app_name
    value: "E-Commerce Monolith"
  - name: deployment_mode
    value: "monolith"

# Define all services with router configuration
services:
  - name: user-service
    type: user_service
    service-router-convention: "rest"    # Use REST convention for this service
    resource-name: user                  # REST convention will use "user" -> "/users"
    path-prefix: "/api/v1"              # Full path prefix for this service
    config:
      storage: memory
      
  - name: auth-service
    type: auth_service
    service-router-convention: "rest"    # Use REST convention for this service
    resource-name: auth                  # REST convention will use "auth" -> "/auth"
    path-prefix: "/api/v1"              # Full path prefix for this service
    config:
      jwt_secret: dev-secret-key
      token_expiry: 3600

  - name: order-service
    type: order_service
    service-router-convention: "rest"    # Use REST convention for this service
    resource-name: order                 # REST convention will use "order" -> "/orders"
    path-prefix: "/api/v1"              # Full path prefix for this service
    config:
      storage: memory
      max_items_per_order: 100
    
  - name: cart-service
    type: cart_service
    service-router-convention: "rest"    # Use REST convention for this service
    resource-name: cart                  # REST convention will use "cart" -> "/carts"
    path-prefix: "/api/v1"              # Full path prefix for this service
    config:
      storage: memory
      session_timeout: 1800

  - name: payment-service
    type: payment_service
    service-router-convention: "rest"    # Use REST convention for this service
    resource-name: payment               # REST convention will use "payment" -> "/payments"
    path-prefix: "/api/v1"              # Full path prefix for this service
    config:
      storage: memory
      currency: USD
    
  - name: invoice-service
    type: invoice_service
    service-router-convention: "rest"    # Use REST convention for this service
    resource-name: invoice               # REST convention will use "invoice" -> "/invoices"
    path-prefix: "/api/v1"              # Full path prefix for this service
    config:
      storage: memory

middlewares:
  - name: logger
    type: request_logger
    config:
      format: "text"
      log_level: "debug"

# Single server with all services
servers:
  - name: monolith
    base-url: http://localhost:8080
    apps:
      - name: monolith-app
        addr: ":8080"
        # ✅ All services listed here → routers auto-generated from services using convention
        services:
          - user-service
          - auth-service
          - order-service
          - cart-service
          - payment-service
          - invoice-service
        # ✅ Routers will be auto-generated with same names as services
        routers:
          - user-service
          - auth-service
          - order-service
          - cart-service
          - payment-service
          - invoice-service
        middlewares: [logger]
