# Production Configuration

configs:
  - name: log_level
    value: "INFO"
  - name: enable_debug
    value: false
  - name: max_connections
    value: 1000
  - name: request_timeout
    value: "30s"
