@baseUrl=http://localhost:3001

### List all users
GET {{baseUrl}}/users

### Get user 1
GET {{baseUrl}}/users/1

### create new user
POST {{baseUrl}}/users

{
  "name": "Rusty",
  "email": "rusty@example.com"
}

### DELETE user 2
DELETE {{baseUrl}}/users/2