# yaml-language-server: $schema=https://lokstra.dev/schema/lokstra.json

# Product Service Deployment (Microservice)
# Only product service running
# Calls order service via HTTP
# Best for: Production microservices deployment
# Performance: Network overhead for cross-service calls

services:
  # Infrastructure Layer
  - name: db
    type: DBService

  - name: cache
    type: CacheService

  # Repository Layer
  - name: product-repo
    type: ProductRepository
    config:
      db_service: db
      cache_service: cache
  
  # Business Logic Layer
  - name: product-svc
    type: ProductService
    config:
      repo_service: product-repo

servers:
  - name: product-server
    deployment-id: product-microservice
    baseUrl: "${PRODUCT_URL:http://localhost:8081}"
    apps:
      - addr: :8081
        routers: [product-api, health-api]
