# Product Service Deployment (Microservice)
# Only product service running
# Calls order service via HTTP
# Best for: Production microservices deployment
# Performance: Network overhead for cross-service calls

services:
  # Infrastructure Layer
  db:
    factory: DBService
  
  cache:
    factory: CacheService
  
  # Repository Layer
  product-repo:
    factory: ProductRepository
    lazy: true
  
  # Business Logic Layer
  product-svc:
    factory: ProductService
    lazy: true

servers:
  - name: product-server
    deploymentId: product-microservice
    protocol: http
    host: 0.0.0.0
    port: 8081
    routers:
      - name: product-api
        basePath: /api
      - name: health-api
        basePath: ""

clientRouters:
  - name: product-api
    deploymentId: product-microservice
    baseUrl: ${PRODUCT_URL:http://localhost:8081/api}
  
  - name: order-api
    baseUrl: ${ORDER_URL:http://localhost:8082/api}
