// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package repository

import (
	"github.com/primadi/lokstra/lokstra_registry"
)

// Auto-register on package import
func init() {
	RegisterOrderRepositoryImpl()
}

// ============================================================
// FILE: order_repository.go
// ============================================================

// RegisterOrderRepositoryImpl registers the order-repository with the registry
// Auto-generated from annotations:
//   - @Service name="order-repository"
func RegisterOrderRepositoryImpl() {
	lokstra_registry.RegisterLazyService("order-repository", func(deps map[string]any, cfg map[string]any) any {
		svc := &OrderRepositoryImpl{
		}
		
		// Call Init() for post-initialization
		if err := svc.Init(); err != nil {
			panic("failed to initialize order-repository: " + err.Error())
		}
		
		return svc
	}, map[string]any{
	})
}


