// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation to auto-register services via init()
// This file imports all packages containing @Service or @RouterService annotations

package main

import (
	_ "github.com/primadi/lokstra/project_templates/02_app_framework/03_enterprise_router_service/modules/order/application"
	_ "github.com/primadi/lokstra/project_templates/02_app_framework/03_enterprise_router_service/modules/order/infrastructure/repository"
	_ "github.com/primadi/lokstra/project_templates/02_app_framework/03_enterprise_router_service/modules/user/application"
	_ "github.com/primadi/lokstra/project_templates/02_app_framework/03_enterprise_router_service/modules/user/infrastructure/repository"
)
