// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package repository

import (
	"github.com/primadi/lokstra/lokstra_registry"
	serviceapi "github.com/primadi/lokstra/serviceapi"
)

// Auto-register on package import
func init() {
	RegisterPostgresTenantStore()
	RegisterPostgresUserStore()
}

// ============================================================
// FILE: tenant_store.go
// ============================================================

// RegisterPostgresTenantStore registers the postgres-tenant-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-tenant-store"
//   - @Inject annotations
func RegisterPostgresTenantStore() {
	lokstra_registry.RegisterLazyService("postgres-tenant-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresTenantStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


// ============================================================
// FILE: user_store.go
// ============================================================

// RegisterPostgresUserStore registers the postgres-user-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-user-store"
//   - @Inject annotations
func RegisterPostgresUserStore() {
	lokstra_registry.RegisterLazyService("postgres-user-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresUserStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


