// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package repository

import (
	"github.com/primadi/lokstra/lokstra_registry"
	serviceapi "github.com/primadi/lokstra/serviceapi"
)

// Auto-register on package import
func init() {
	RegisterPostgresTenantStore()
}

// ============================================================
// FILE: tenant_store.go
// ============================================================

// RegisterPostgresTenantStore registers the postgres-tenant-store with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-tenant-store"
//   - @Inject annotations
func RegisterPostgresTenantStore() {
	lokstra_registry.RegisterLazyService("postgres-tenant-store", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresTenantStore{
			dbPool: deps["db_auth"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_auth", },
	})
}


