# yaml-language-server: $schema=../../schema/lokstra.json

# UI Renderer Demo Configuration for User Management
# Complete example showing declarative UI development capabilities

server:
  name: "ui_renderer_demo"

services:
  # Logger service for debugging
  - name: "logger"
    type: "lokstra.logger"
    config:
      level: "info"
      format: "console"
      output: "stdout"

  # UI Renderer service with development-friendly settings
  - name: "ui_renderer"
    type: "lokstra.ui_renderer"
    config:
      template_dir: "services/ui_renderer/templates"
      theme: "light"
      cache_templates: false
      hot_reload: true
      minify_output: false
      preline_version: "2.0.0"
      htmx_config:
        version: "1.9.0"
        global_config:
          timeout: 10000
          history_cache_size: 15
      alpine_config:
        version: "3.13.0"
        plugins:
          - "focus"
          - "mask"
          - "intersect"
          - "persist"
      tailwind_config:
        content:
          - "./services/ui_renderer/templates/**/*.html"
          - "./cmd/examples/ui_renderer_demo/**/*.html"
        theme:
          extend:
            colors:
              primary: "#3b82f6"
              secondary: "#64748b"
              success: "#10b981"
              warning: "#f59e0b"
              error: "#ef4444"
      component_dirs:
        - "./services/ui_renderer/templates"
        - "./cmd/examples/ui_renderer_demo/components"

  # HTTP listener to serve the UI
  - name: "http_server"
    type: "lokstra.http_listener"
    config:
      addr: ":8080"
      read_timeout: "30s"
      write_timeout: "30s"
      idle_timeout: "60s"

apps:
  - name: "user_management_ui"
    address: ":8080"
    groups:
      - prefix: "/"
        routes:
          # Main pages
          - method: "GET"
            path: "/"
            handler: "render_dashboard"
          - method: "GET"
            path: "/users"
            handler: "render_users_list"
          - method: "GET"
            path: "/users/new"
            handler: "render_user_form"
          - method: "GET"
            path: "/users/{id}/edit"
            handler: "render_user_edit"
          
          # HTMX endpoints for dynamic content
          - method: "POST"
            path: "/users"
            handler: "create_user"
          - method: "PUT"
            path: "/users/{id}"
            handler: "update_user"
          - method: "DELETE"
            path: "/users/{id}"
            handler: "delete_user"
          - method: "GET"
            path: "/users/{id}/details"
            handler: "render_user_details"
          
          # Component endpoints
          - method: "GET"
            path: "/components/user-table"
            handler: "render_user_table_component"
          - method: "GET"
            path: "/components/user-form"
            handler: "render_user_form_component"

        mount_static:
          - prefix: "/static"
            folder: ["./static"]
          - prefix: "/assets"
            folder: ["./assets"]
