# yaml-language-server: $schema=../../schema/lokstra.json

# UI Renderer Service Configuration
# Enables declarative UI development for Go applications using modern web technologies

services:
  # Basic UI Renderer Service
  - name: "ui_renderer"
    type: "lokstra.ui_renderer"
    config:
      template_dir: "services/ui_renderer/templates"
      theme: "light"
      cache_templates: true
      hot_reload: false
      minify_output: false

  # Development UI Renderer with Hot Reload
  - name: "ui_renderer_dev"
    type: "lokstra.ui_renderer"
    config:
      template_dir: "services/ui_renderer/templates"
      theme: "auto"
      cache_templates: false
      hot_reload: true
      minify_output: false
      preline_version: "2.0.0"
      htmx_config:
        version: "1.9.0"
        global_config:
          timeout: 10000
          history_cache_size: 15
      alpine_config:
        version: "3.13.0"
        plugins:
          - "focus"
          - "mask"
          - "intersect"
      component_dirs:
        - "./components"
        - "./widgets"

  # Production UI Renderer with Optimization
  - name: "ui_renderer_prod"
    type: "lokstra.ui_renderer"
    config:
      template_dir: "services/ui_renderer/templates"
      theme: "light"
      cache_templates: true
      hot_reload: false
      minify_output: true
      preline_version: "2.0.0"
      tailwind_config:
        content:
          - "./templates/**/*.html"
          - "./static/**/*.js"
          - "./components/**/*.html"
        theme:
          extend:
            colors:
              primary: "#3b82f6"
              secondary: "#64748b"
      htmx_config:
        version: "1.9.0"
        global_config:
          timeout: 5000
          history_cache_size: 10
      alpine_config:
        version: "3.13.0"
        plugins:
          - "focus"
          - "persist"

  # Custom Theme UI Renderer
  - name: "ui_renderer_custom"
    type: "lokstra.ui_renderer"
    config:
      template_dir: "./custom_templates"
      theme: "dark"
      cache_templates: true
      hot_reload: false
      minify_output: false
      preline_version: "latest"
      tailwind_config:
        content:
          - "./custom_templates/**/*.html"
          - "./assets/**/*.js"
        theme:
          extend:
            colors:
              primary: "#10b981"
              secondary: "#374151"
              accent: "#f59e0b"
            fontFamily:
              sans: ["Inter", "sans-serif"]
      component_dirs:
        - "./custom_components"
        - "./shared/ui"
