// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @InjectCfgValue, @Route

package main

import (
	"github.com/primadi/lokstra/lokstra_registry"
	serviceapi "github.com/primadi/lokstra/serviceapi"
)

// Auto-register on package import
func init() {
	RegisterEmailService()
}

// ============================================================
// FILE: email_service.go
// ============================================================

// RegisterEmailService registers the email-api-service with the registry
// Auto-generated from annotations:
//   - @Service name="email-api-service"
//   - @Inject annotations
func RegisterEmailService() {
	lokstra_registry.RegisterLazyService("email-api-service", func(deps map[string]any, cfg map[string]any) any {
		svc := &EmailService{
			EmailSender: deps["email_smtp"].(serviceapi.EmailSender),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "email_smtp", },
	})
}


