# Monolith Configuration
# Single server hosts all services

services:
  - name: user-service
    type: user-service
    config:
      deployment_name: "monolith-user-service"

  - name: order-service
    type: order-service
    config:
      deployment_name: "monolith-order-service"

routers:
  - name: main-router
    routes:
      - name: Home
        path: /
        handler: HomeHandler
      - name: GetUsers
        path: /users
        handler: user-service.GetUsers
      - name: GetOrders
        path: /orders
        handler: order-service.GetOrders

servers:
  - name: monolith-server
    apps:
      - addr: ":3010"
        routers:
          - main-router
