// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @Handler, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package handler

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	domain "github.com/primadi/lokstra/project_templates/02_app_framework/03_tenant_management/domain"
	repository "github.com/primadi/lokstra/project_templates/02_app_framework/03_tenant_management/repository"
	request "github.com/primadi/lokstra/core/request"
)

// Auto-register on package import
func init() {
	RegisterTenantHandler()
}

// ============================================================
// FILE: tenant_handker.go
// ============================================================

// TenantHandlerRemote implements TenantHandlerInterface with HTTP proxy
// Auto-generated from TenantHandler interface methods
type TenantHandlerRemote struct {
	proxyService *proxy.Service
}

// NewTenantHandlerRemote creates a new remote tenant-handler proxy
func NewTenantHandlerRemote(proxyService *proxy.Service) *TenantHandlerRemote {
	return &TenantHandlerRemote{
		proxyService: proxyService,
	}
}

// ActivateTenant via HTTP
// Generated from: @Route "POST /{id}/activate"
func (s *TenantHandlerRemote) ActivateTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "ActivateTenant", p)
}

// CreateTenant via HTTP
// Generated from: @Route "POST /"
func (s *TenantHandlerRemote) CreateTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "CreateTenant", p)
}

// DeleteTenant via HTTP
// Generated from: @Route "DELETE /{id}"
func (s *TenantHandlerRemote) DeleteTenant(p *request.Context) error {
	return proxy.Call(s.proxyService, "DeleteTenant", p)
}

// GetTenant via HTTP
// Generated from: @Route "GET /{id}"
func (s *TenantHandlerRemote) GetTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "GetTenant", p)
}

// ListTenants via HTTP
// Generated from: @Route "GET /"
func (s *TenantHandlerRemote) ListTenants(p *request.Context) ([]*domain.Tenant, error) {
	return proxy.CallWithData[[]*domain.Tenant](s.proxyService, "ListTenants", p)
}

// SuspendTenant via HTTP
// Generated from: @Route "POST /{id}/suspend"
func (s *TenantHandlerRemote) SuspendTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "SuspendTenant", p)
}

// UpdateTenant via HTTP
// Generated from: @Route "PUT /{id}"
func (s *TenantHandlerRemote) UpdateTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "UpdateTenant", p)
}


func TenantHandlerFactory(deps map[string]any, config map[string]any) any {
	svc := &TenantHandler{
		TenantRepository: deps["@repository.tenant-repository"].(repository.TenantRepository),
		UserRepository: deps["@repository.user-repository"].(repository.UserRepository),
	}
	
	return svc
}

// TenantHandlerRemoteFactory creates a remote HTTP client for TenantHandlerInterface
// Auto-generated from @Handler annotation
func TenantHandlerRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewTenantHandlerRemote(proxyService)
}

// RegisterTenantHandler registers the tenant-handler with the registry
// Auto-generated from annotations:
//   - @Handler name="tenant-handler", prefix="${api-auth-prefix:/api/auth}/core/tenants"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterTenantHandler() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("tenant-handler-factory",
		TenantHandlerFactory,
		TenantHandlerRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/core/tenants",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"ActivateTenant": {
					Path: "POST /{id}/activate",
				},
				"CreateTenant": {
					Path: "POST /",
				},
				"DeleteTenant": {
					Path: "DELETE /{id}",
				},
				"GetTenant": {
					Path: "GET /{id}",
				},
				"ListTenants": {
					Path: "GET /",
				},
				"SuspendTenant": {
					Path: "POST /{id}/suspend",
				},
				"UpdateTenant": {
					Path: "PUT /{id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("tenant-handler",
		"tenant-handler-factory",
		map[string]any{
			"depends-on": []string{ "@repository.tenant-repository", "@repository.user-repository", },
		})
}


