// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Inject, @Route

package application

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	domain "github.com/primadi/lokstra/docs/00-introduction/examples/full-framework/01_enterprise_router_service/modules/user/domain"
)

// Auto-register on package import
func init() {
	RegisterUserServiceImpl()
}

// ============================================================
// FILE: user_service.go
// ============================================================

// UserServiceImplRemote implements UserServiceImplInterface with HTTP proxy
// Auto-generated from UserServiceImpl interface methods
type UserServiceImplRemote struct {
	proxyService *proxy.Service
}

// NewUserServiceImplRemote creates a new remote user-service proxy
func NewUserServiceImplRemote(proxyService *proxy.Service) *UserServiceImplRemote {
	return &UserServiceImplRemote{
		proxyService: proxyService,
	}
}

// Activate via HTTP
// Generated from: @Route "POST /users/{id}/activate"
func (s *UserServiceImplRemote) Activate(p *domain.ActivateUserRequest) error {
	return proxy.Call(s.proxyService, "Activate", p)
}

// Create via HTTP
// Generated from: @Route "POST /users"
func (s *UserServiceImplRemote) Create(p *domain.CreateUserRequest) (*domain.User, error) {
	return proxy.CallWithData[*domain.User](s.proxyService, "Create", p)
}

// Delete via HTTP
// Generated from: @Route "DELETE /users/{id}"
func (s *UserServiceImplRemote) Delete(p *domain.DeleteUserRequest) error {
	return proxy.Call(s.proxyService, "Delete", p)
}

// GetByID via HTTP
// Generated from: @Route "GET /users/{id}"
func (s *UserServiceImplRemote) GetByID(p *domain.GetUserRequest) (*domain.User, error) {
	return proxy.CallWithData[*domain.User](s.proxyService, "GetByID", p)
}

// List via HTTP
// Generated from: @Route "GET /users"
func (s *UserServiceImplRemote) List(p *domain.ListUsersRequest) ([]*domain.User, error) {
	return proxy.CallWithData[[]*domain.User](s.proxyService, "List", p)
}

// Suspend via HTTP
// Generated from: @Route "POST /users/{id}/suspend"
func (s *UserServiceImplRemote) Suspend(p *domain.SuspendUserRequest) error {
	return proxy.Call(s.proxyService, "Suspend", p)
}

// Update via HTTP
// Generated from: @Route "PUT /users/{id}"
func (s *UserServiceImplRemote) Update(p *domain.UpdateUserRequest) (*domain.User, error) {
	return proxy.CallWithData[*domain.User](s.proxyService, "Update", p)
}


func UserServiceImplFactory(deps map[string]any, config map[string]any) any {
	return &UserServiceImpl{
		UserRepo: deps["user-repository"].(domain.UserRepository),
	}
}

// UserServiceImplRemoteFactory creates a remote HTTP client for UserServiceImplInterface
// Auto-generated from @RouterService annotation
func UserServiceImplRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewUserServiceImplRemote(proxyService)
}

// RegisterUserServiceImpl registers the user-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="user-service", prefix="/api"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterUserServiceImpl() {
	// Register service type with router configuration
	lokstra_registry.RegisterServiceType("user-service-factory",
		UserServiceImplFactory,
		UserServiceImplRemoteFactory,
		deploy.WithRouter(&deploy.ServiceTypeRouter{
			PathPrefix:  "/api",
			Middlewares: []string{ "recovery", "request-logger" },
			CustomRoutes: map[string]string{
				"Activate":  "POST /users/{id}/activate",
				"Create":  "POST /users",
				"Delete":  "DELETE /users/{id}",
				"GetByID":  "GET /users/{id}",
				"List":  "GET /users",
				"Suspend":  "POST /users/{id}/suspend",
				"Update":  "PUT /users/{id}",
			},
		}),
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("user-service",
		"user-service-factory",
		map[string]any{
			"depends-on": []string{ "user-repository",  },
		})
}

