# Microservices Configuration - User Service
# Separate microservice for user management and authentication

configs:
  - name: server-name
    value: ${SERVER_NAME:user-service}
  
  - name: deployment-strategy
    value: microservice

# Only services needed for users
services:
  - name: db-service
    type: db
    config:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:5432}
      database: ${DB_NAME:users}

  - name: user-service
    type: user
    config: {}

# User microservice configuration
servers:
  - name: user-service
    baseUrl: ${USER_SERVICE_URL:http://localhost}
    deployment-id: microservice
    apps:
      - addr: ":8082"
        routers: [user-api, health-api]
