### Home page
GET http://localhost:3040/

### Get current configuration
GET http://localhost:3040/status

### Trigger configuration update
POST http://localhost:3040/update

### Get configuration again (should see changes)
GET http://localhost:3040/status
