# Docker Compose for Monolith Deployment
# Single container running all applications

version: "3.8"

services:
  lokstra-monolith:
    build: .
    container_name: lokstra-monolith
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=monolith-config.yaml
    volumes:
      - ./monolith-config.yaml:/root/config.yaml:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: lokstra-network
