# Monolith Deployment Configuration
# All apps running in a single server instance

server:
  name: "lokstra-monolith"
  port: 8080
  host: "0.0.0.0"

# Global middleware for all apps
middleware:
  - name: "cors"
    enabled: true
    config:
      allow_origins: ["*"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["*"]
  - name: "request_logger"
    enabled: true

# All three applications in one deployment
apps:
  # User API Application
  - name: "user-api"
    enabled: true
    routes:
      - path: "/api/users"
        method: "GET"
        handler: "apps.GetUsers"
      - path: "/api/users/{id}"
        method: "GET"
        handler: "apps.GetUser"
      - path: "/api/users"
        method: "POST"
        handler: "apps.CreateUser"
    middleware:
      - name: "recovery"
        enabled: true

  # Order API Application  
  - name: "order-api"
    enabled: true
    routes:
      - path: "/api/orders"
        method: "GET"
        handler: "apps.GetOrders"
      - path: "/api/orders/{id}"
        method: "GET"
        handler: "apps.GetOrder"
      - path: "/api/orders"
        method: "POST"
        handler: "apps.CreateOrder"
    middleware:
      - name: "recovery"
        enabled: true

  # Dashboard HTMX Application
  - name: "dashboard"
    enabled: true
    routes:
      - path: "/dashboard"
        method: "GET"
        handler: "apps.DashboardHome"
      - path: "/dashboard/users"
        method: "GET"
        handler: "apps.DashboardUsers"
      - path: "/dashboard/orders"
        method: "GET"
        handler: "apps.DashboardOrders"
    middleware:
      - name: "recovery"
        enabled: true

# Health check endpoint
health:
  enabled: true
  path: "/health"