# Order API Microservice Configuration
# Dedicated service for order management

server:
  name: "lokstra-order-service"
  port: 8082
  host: "0.0.0.0"

# Middleware for order service
middleware:
  - name: "cors"
    enabled: true
    config:
      allow_origins: ["*"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["*"]
  - name: "request_logger"
    enabled: true
  - name: "recovery"
    enabled: true

# Only order-related functionality
apps:
  - name: "order-api"
    enabled: true
    routes:
      - path: "/api/orders"
        method: "GET"
        handler: "apps.GetOrders"
      - path: "/api/orders/{id}"
        method: "GET"
        handler: "apps.GetOrder"
      - path: "/api/orders"
        method: "POST"
        handler: "apps.CreateOrder"

# Health check endpoint
health:
  enabled: true
  path: "/health"