# User API Microservice Configuration
# Dedicated service for user management

server:
  name: "lokstra-user-service"
  port: 8081
  host: "0.0.0.0"

# Middleware for user service
middleware:
  - name: "cors"
    enabled: true
    config:
      allow_origins: ["*"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["*"]
  - name: "request_logger"
    enabled: true
  - name: "recovery"
    enabled: true

# Only user-related functionality
apps:
  - name: "user-api"
    enabled: true
    routes:
      - path: "/api/users"
        method: "GET"
        handler: "apps.GetUsers"
      - path: "/api/users/{id}"
        method: "GET"
        handler: "apps.GetUser"
      - path: "/api/users"
        method: "POST"
        handler: "apps.CreateUser"

# Health check endpoint
health:
  enabled: true
  path: "/health"