# Base configuration - shared across environments
middlewares:
  - name: api-logger
    type: logger
    config:
      level: "info"
      format: "structured"
      
  - name: api-cors
    type: cors
    config:
      origins: ["http://localhost:3000", "http://localhost:8080"]
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      
  - name: admin-auth
    type: auth
    config:
      secret: "${JWT_SECRET:default-admin-secret}"
      expiry: "24h"

  # Additional middleware for route-level configuration
  - name: rate-limit
    type: rate-limit
    config:
      requests_per_minute: 60

  - name: cache
    type: cache
    config:
      ttl: "5m"

  - name: monitoring
    type: monitoring
    config:
      enabled: true

  - name: audit-log
    type: audit-log
    config:
      level: "info"

services:
  - name: main-db
    type: database
    config:
      host: "${DB_HOST:localhost}"
      port: "${DB_PORT:5432}"
      database: "${DB_NAME:lokstra_app}"
      user: "${DB_USER:postgres}"
      password: "${DB_PASSWORD:password}"
      ssl_mode: "${DB_SSL_MODE:disable}"
      
  - name: session-cache
    type: cache
    config:
      addr: "${REDIS_ADDR:localhost:6379}"
      password: "${REDIS_PASSWORD:}"
      db: "${REDIS_DB:0}"