# yaml-language-server: $schema=../../../../../../schema/group-include.json

# This file demonstrates a complete group include configuration
# It will be loaded by a parent group via load_from

# Direct routes that will be added to the parent group
routes:
  - method: GET
    path: /health
    handler: health.check
  - method: GET
    path: /version
    handler: version.get
  - method: POST
    path: /webhook
    handler: webhook.receive
    middleware:
      - name: webhook_auth
        config:
          secret: "${WEBHOOK_SECRET:default-secret}"

# Nested groups with their own middleware and routes
groups:
  - prefix: /admin
    middleware:
      - name: admin_auth
        config:
          required_role: admin
    routes:
      - method: GET
        path: /dashboard
        handler: admin.dashboard
      - method: GET
        path: /users
        handler: admin.list_users
      - method: DELETE
        path: /users/:id
        handler: admin.delete_user

  - prefix: /public
    routes:
      - method: GET
        path: /docs
        handler: docs.serve
      - method: GET
        path: /status
        handler: status.check

# Static file mounts
mount_static:
  - prefix: /static
    folder: ./public/static
  - prefix: /uploads
    folder: ./data/uploads

# SPA mount for admin panel
mount_spa:
  - prefix: /admin-ui
    fallback_file: ./admin-ui/dist/index.html
