# yaml-language-server: $schema=https://lokstra.dev/schema/lokstra-group.json

# This is an example of a group include file that can be loaded via load_from
# in a group configuration. It contains routes, groups, and mount points that
# will be merged into the parent group.

routes:
  - method: GET
    path: /users
    handler: user.list
  # - method: POST
  #   path: /users
  #   handler: user.create
  # - method: GET
  #   path: /users/:id
  #   handler: user.get
  # - method: PUT
  #   path: /users/:id
  #   handler: user.update
  # - method: DELETE
  #   path: /users/:id
  #   handler: user.delete

# groups:
#   - prefix: /admin
#     routes:
      # - method: GET
      #   path: /stats
      #   handler: admin.stats
    #   - method: GET
    #     path: /users
    #     handler: admin.users
    # middleware:
    #   - name: admin_auth
    #     config:
    #       role: admin

mount_static:
  - prefix: /uploads
    folder: [./uploads]
  - prefix: /docs
    folder: [./documentation]
  - prefix: /dashboard
    spa: true
    folder: [./frontend/dist/index.html]
