printer_types:
  lx310:
    ESC_INIT: [27, 64]
    ESC_BOLD_ON: [27, 69]
    ESC_BOLD_OFF: [27, 70]
    ESC_FEED_AND_CUT: [27, 105]

  tm-u220:
    ESC_INIT: [27, 64]
    ESC_FEED_AND_CUT: [29, 86, 66, 0]

printers:
  - name: kasir
    type: lx310
    device: LPT1
  - name: lab
    type: tm-u220
    device: "\\\\LAB-PC\\EpsonLab"

default: kasir
