// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package application

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	request "github.com/primadi/lokstra/core/request"
	domain "github.com/primadi/lokstra/project_templates/02_app_framework/03_tenant_management/domain"
	repository "github.com/primadi/lokstra/project_templates/02_app_framework/03_tenant_management/repository"
)

// Auto-register on package import
func init() {
	RegisterTenantService()
}

// ============================================================
// FILE: tenant_service.go
// ============================================================

// TenantServiceRemote implements TenantServiceInterface with HTTP proxy
// Auto-generated from TenantService interface methods
type TenantServiceRemote struct {
	proxyService *proxy.Service
}

// NewTenantServiceRemote creates a new remote tenant-service proxy
func NewTenantServiceRemote(proxyService *proxy.Service) *TenantServiceRemote {
	return &TenantServiceRemote{
		proxyService: proxyService,
	}
}

// ActivateTenant via HTTP
// Generated from: @Route "POST /{id}/activate"
func (s *TenantServiceRemote) ActivateTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "ActivateTenant", p)
}

// CreateTenant via HTTP
// Generated from: @Route "POST /"
func (s *TenantServiceRemote) CreateTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "CreateTenant", p)
}

// DeleteTenant via HTTP
// Generated from: @Route "DELETE /{id}"
func (s *TenantServiceRemote) DeleteTenant(p *request.Context) error {
	return proxy.Call(s.proxyService, "DeleteTenant", p)
}

// GetTenant via HTTP
// Generated from: @Route "GET /{id}"
func (s *TenantServiceRemote) GetTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "GetTenant", p)
}

// ListTenants via HTTP
// Generated from: @Route "GET /"
func (s *TenantServiceRemote) ListTenants(p *request.Context) ([]*domain.Tenant, error) {
	return proxy.CallWithData[[]*domain.Tenant](s.proxyService, "ListTenants", p)
}

// SuspendTenant via HTTP
// Generated from: @Route "POST /{id}/suspend"
func (s *TenantServiceRemote) SuspendTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "SuspendTenant", p)
}

// UpdateTenant via HTTP
// Generated from: @Route "PUT /{id}"
func (s *TenantServiceRemote) UpdateTenant(p *request.Context) (*domain.Tenant, error) {
	return proxy.CallWithData[*domain.Tenant](s.proxyService, "UpdateTenant", p)
}


func TenantServiceFactory(deps map[string]any, config map[string]any) any {
	svc := &TenantService{
		TenantStore: deps["@store.tenant-store"].(repository.TenantStore),
		UserStore: deps["@store.user-store"].(repository.UserStore),
	}
	
	return svc
}

// TenantServiceRemoteFactory creates a remote HTTP client for TenantServiceInterface
// Auto-generated from @RouterService annotation
func TenantServiceRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewTenantServiceRemote(proxyService)
}

// RegisterTenantService registers the tenant-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="tenant-service", prefix="${api-auth-prefix:/api/auth}/core/tenants"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterTenantService() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("tenant-service-factory",
		TenantServiceFactory,
		TenantServiceRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "${api-auth-prefix:/api/auth}/core/tenants",
			Middlewares: []string{ "recovery", "request_logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"ActivateTenant": {
					Path: "POST /{id}/activate",
				},
				"CreateTenant": {
					Path: "POST /",
				},
				"DeleteTenant": {
					Path: "DELETE /{id}",
				},
				"GetTenant": {
					Path: "GET /{id}",
				},
				"ListTenants": {
					Path: "GET /",
				},
				"SuspendTenant": {
					Path: "POST /{id}/suspend",
				},
				"UpdateTenant": {
					Path: "PUT /{id}",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("tenant-service",
		"tenant-service-factory",
		map[string]any{
			"depends-on": []string{ "@store.tenant-store", "@store.user-store", },
		})
}


