// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation to auto-register services via init()
// This file imports all packages containing @Service or @Handler annotations

package main

import (
	_ "github.com/primadi/lokstra/project_templates/02_app_framework/03_tenant_management/handler"
	_ "github.com/primadi/lokstra/project_templates/02_app_framework/03_tenant_management/repository/postgres"
)
