// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation to auto-register services via init()
// This file imports all packages containing @Service or @Handler annotations

package main

import (
	_ "examples/test-local/modules/order/application"
	_ "examples/test-local/modules/order/infrastructure/repository"
	_ "examples/test-local/modules/user/application"
	_ "examples/test-local/modules/user/infrastructure/repository"
)
