// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @RouterService, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package application

import (
	"github.com/primadi/lokstra/core/deploy"
	"github.com/primadi/lokstra/core/proxy"
	"github.com/primadi/lokstra/lokstra_registry"
	userDomain "github.com/primadi/lokstra/project_templates/02_app_framework/01_enterprise_router_service/modules/user/domain"
	domain "github.com/primadi/lokstra/project_templates/02_app_framework/01_enterprise_router_service/modules/order/domain"
)

// Auto-register on package import
func init() {
	RegisterOrderServiceImpl()
}

// ============================================================
// FILE: order_service.go
// ============================================================

// OrderServiceImplRemote implements OrderServiceImplInterface with HTTP proxy
// Auto-generated from OrderServiceImpl interface methods
type OrderServiceImplRemote struct {
	proxyService *proxy.Service
}

// NewOrderServiceImplRemote creates a new remote order-service proxy
func NewOrderServiceImplRemote(proxyService *proxy.Service) *OrderServiceImplRemote {
	return &OrderServiceImplRemote{
		proxyService: proxyService,
	}
}

// Cancel via HTTP
// Generated from: @Route "POST /orders/{id}/cancel"
func (s *OrderServiceImplRemote) Cancel(p *domain.CancelOrderRequest) error {
	return proxy.Call(s.proxyService, "Cancel", p)
}

// Create via HTTP
// Generated from: @Route "POST /orders"
func (s *OrderServiceImplRemote) Create(p *domain.CreateOrderRequest) (*domain.Order, error) {
	return proxy.CallWithData[*domain.Order](s.proxyService, "Create", p)
}

// Delete via HTTP
// Generated from: @Route "DELETE /orders/{id}"
func (s *OrderServiceImplRemote) Delete(p *domain.DeleteOrderRequest) error {
	return proxy.Call(s.proxyService, "Delete", p)
}

// GetByID via HTTP
// Generated from: @Route "GET /orders/{id}"
func (s *OrderServiceImplRemote) GetByID(p *domain.GetOrderRequest) (*domain.Order, error) {
	return proxy.CallWithData[*domain.Order](s.proxyService, "GetByID", p)
}

// List via HTTP
// Generated from: @Route "GET /orders"
func (s *OrderServiceImplRemote) List(p *domain.ListOrdersRequest) ([]*domain.Order, error) {
	return proxy.CallWithData[[]*domain.Order](s.proxyService, "List", p)
}

// UpdateStatus via HTTP
// Generated from: @Route "PUT /orders/{id}/status"
func (s *OrderServiceImplRemote) UpdateStatus(p *domain.UpdateOrderStatusRequest) (*domain.Order, error) {
	return proxy.CallWithData[*domain.Order](s.proxyService, "UpdateStatus", p)
}


func OrderServiceImplFactory(deps map[string]any, config map[string]any) any {
	svc := &OrderServiceImpl{
		OrderRepo: deps["@store.order-repository"].(domain.OrderRepository),
		UserService: deps["user-service"].(userDomain.UserService),
	}
	
	return svc
}

// OrderServiceImplRemoteFactory creates a remote HTTP client for OrderServiceImplInterface
// Auto-generated from @RouterService annotation
func OrderServiceImplRemoteFactory(deps, config map[string]any) any {
	proxyService, ok := config["remote"].(*proxy.Service)
	if !ok {
		panic("remote factory requires 'remote' (proxy.Service) in config")
	}
	return NewOrderServiceImplRemote(proxyService)
}

// RegisterOrderServiceImpl registers the order-service with the registry
// Auto-generated from annotations:
//   - @RouterService name="order-service", prefix="/api"
//   - @Inject annotations
//   - @Route annotations on methods
func RegisterOrderServiceImpl() {
	// Register service type with router configuration
	lokstra_registry.RegisterRouterServiceType("order-service-factory",
		OrderServiceImplFactory,
		OrderServiceImplRemoteFactory,
		&deploy.ServiceTypeConfig{
			PathPrefix:  "/api",
			Middlewares: []string{ "recovery", "request-logger" },
			RouteOverrides: map[string]deploy.RouteConfig{
				"Cancel": {
					Path: "POST /orders/{id}/cancel",
				},
				"Create": {
					Path: "POST /orders",
				},
				"Delete": {
					Path: "DELETE /orders/{id}",
				},
				"GetByID": {
					Path: "GET /orders/{id}",
				},
				"List": {
					Path: "GET /orders",
				},
				"UpdateStatus": {
					Path: "PUT /orders/{id}/status",
				},
			},
		},
	)

	// Register lazy service with auto-detected dependencies
	lokstra_registry.RegisterLazyService("order-service",
		"order-service-factory",
		map[string]any{
			"depends-on": []string{ "@store.order-repository", "user-service", },
		})
}


