# yaml-language-server: $schema=../../../../core/deploy/schema/lokstra.schema.json
# ========================================
# CRUD API - YAML Configuration
# ========================================
# This config is used when running with: go run main.go --mode=config

# Global configs
configs:
  APP_NAME: "User CRUD API"
  APP_VERSION: "1.0.0"

# Service definitions
service-definitions:
  database:
    type: database-factory
    config:
      seed_data: true
  
  user-service:
    type: user-service-factory
    depends-on: [database]  # Auto lazy-loaded!

# Deployment configuration
deployments:
  development:
    servers:
      api:
        base-url: http://localhost
        addr: ":3002"
        routers: [api]
