// AUTO-GENERATED CODE - DO NOT EDIT
// Generated by lokstra-annotation from annotations in this folder
// Annotations: @Handler, @Service, @Inject, @Route
//
// @Inject supports:
//   - "service-name"          : Direct service injection
//   - "@config.key"           : Service name from config value
//   - "cfg:config.key"        : Config value injection
//   - "cfg:@config.key"       : Config value via indirection

package postgres

import (
	"github.com/primadi/lokstra/lokstra_registry"
	serviceapi "github.com/primadi/lokstra/serviceapi"
)

// Auto-register on package import
func init() {
	RegisterPostgresTenantRepository()
	RegisterPostgresUserRepository()
}

// ============================================================
// FILE: tenant_repository.go
// ============================================================

// RegisterPostgresTenantRepository registers the postgres-tenant-repository with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-tenant-repository"
//   - @Inject annotations
func RegisterPostgresTenantRepository() {
	lokstra_registry.RegisterLazyService("postgres-tenant-repository", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresTenantRepository{
			dbPool: deps["db_main"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_main", },
	})
}


// ============================================================
// FILE: user_repository.go
// ============================================================

// RegisterPostgresUserRepository registers the postgres-user-repository with the registry
// Auto-generated from annotations:
//   - @Service name="postgres-user-repository"
//   - @Inject annotations
func RegisterPostgresUserRepository() {
	lokstra_registry.RegisterLazyService("postgres-user-repository", func(deps map[string]any, cfg map[string]any) any {
		svc := &PostgresUserRepository{
			dbPool: deps["db_main"].(serviceapi.DbPool),
		}
		
		return svc
	}, map[string]any{
		"depends-on": []string{ "db_main", },
	})
}


