# ========================================
# Multi-Deployment Configuration
# ========================================
#
# This single config defines 3 different deployments:
#   1. monolith     - All services in one process (dev/small apps)
#   2. user-service - Only user endpoints (microservices)
#   3. order-service - Only order endpoints (microservices)
#

# ========================================
# Service Definitions (Global) - MAP format
# ========================================

services:
  database:
    type: database-factory

  user-service:
    type: user-service-factory
    depends-on:
      - database

  order-service:
    type: order-service-factory
    depends-on:
      - database
      - user-service  # Can be local OR remote

# ========================================
# Remote Services (for microservices) - MAP format
# ========================================

remote-services:
  user-service-remote:
    url: "http://localhost:3004"
    resource: "user"
    resource-plural: "users"

# ========================================
# Deployments - MAP format
# ========================================

deployments:
  # ========================================
  # MONOLITH: All services in one process
  # ========================================
  monolith:
    servers:
      api:
        base-url: "http://localhost:3003"
        apps:
          - port: 3003
            services:
              - database
              - user-service
              - order-service

  # ========================================
  # USER SERVICE: Only user-related endpoints
  # ========================================
  user-service:
    servers:
      user-api:
        base-url: "http://localhost:3004"
        apps:
          - port: 3004
            services:
              - database
              - user-service

  # ========================================
  # ORDER SERVICE: Order endpoints + remote user service
  # ========================================
  order-service:
    servers:
      order-api:
        base-url: "http://localhost:3005"
        apps:
          - port: 3005
            services:
              - database
              - order-service
            remote-services:
              - user-service-remote  # Uses HTTP client to call user-service
