# yaml-language-server: $schema=../../../../core/deploy/schema/lokstra.schema.json
# ========================================
# Multi-Deployment Configuration
# ========================================
#
# This single config defines 3 different deployments:
#   1. monolith     - All services in one process (dev/small apps)
#   2. user-service - Only user endpoints (microservices)
#   3. order-service - Only order endpoints (microservices)
#

# ========================================
# Service Definitions (Global) - MAP format
# ========================================

service-definitions:
  database:
    type: database-factory

  user-service:
    type: user-service-factory
    depends-on:
      - database

  order-service:
    type: order-service-factory
    depends-on:
      - database
      - user-service  # Can be local OR remote

# ========================================
# Remote Service Definitions (for microservices) - MAP format
# ========================================

remote-service-definitions:
  user-service-remote:
    url: "http://localhost:3004"
    resource: "user"
    resource-plural: "users"

# ========================================
# Deployments - MAP format
# ========================================

deployments:
  # ========================================
  # MONOLITH: All services in one process
  # ========================================
  monolith:
    servers:
      api-server:
        base-url: "http://localhost"
        # Server-level services (shared across all apps)
        required-services:
          - database
          - user-service
          - order-service
        apps:
          - addr: ":3003"
            routers: [monolith-api]

  # ========================================
  # MICROSERVICE: each service in its own process 
  # ========================================
  microservice:
    servers:
      user-server:
        base-url: "http://localhost"
        # Server-level services (shared infrastructure)
        required-services:
          - database
          - user-service
        apps:
          - addr: ":3004"
            routers: [user-api]

      order-server:
        base-url: "http://localhost"
        # Server-level services (shared infrastructure)
        required-services:
          - database
          - order-service
        # Server-level remote services (shared HTTP clients)
        required-remote-services:
          - user-service-remote
        apps:
          - addr: ":3005"
            routers: [order-api]
